from command.handle import eeprom
from command.handle import io
from command.handle import signal_measure
from command.handle import system
from command.handle import sn
from command.handle import uart
from command.handle import i2c
from command.handle import spi
from command.handle import spi_slave
from command.handle import hdq_slave
from command.handle import swd
from command.handle import gpio